name: geocoder
description: Forward and reverse geocoding.
version: 0.2.1
author: Aloïs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin
      ios:
        pluginClass: GeocoderPlugin
